apiVersion: v1 
kind: Service
metadata:
  name: postgres-service-deploy
  labels:
    name: postgres-service 
    app: voting-app
spec:
  selector:
    name: postgres-deploy
    app: voting-app
  ports:
    - port: 5432
      targetPort: 5432