apiVersion: v1 
kind: Service
metadata:
  name: redis-service-deploy
  labels:
    name: redis-service 
    app: voting-app
spec:
  selector:
    name: redis-deploy
    app: voting-app
  ports:
    - port: 6379
      targetPort: 6379