apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
   name: redis-deploy
   app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-deploy
      app: voting-app  
  template:
    metadata:
     name: redis-pod
     labels:
       name: redis-deploy
       app: voting-app
    spec:
     containers:
       - name: redis
         image: redis
         ports:
         - containerPort: 6379
    

    