apiVersion: apps/v1
kind: Deployment
metadata: 
 name: voting-app
 labels:
  name: result-app-deploy
  app: voting-app
spec:
 replicas: 1
 selector:
   matchLabels:
    name: result-app-deploy
    app: voting-app
 template:
   metadata:
     name: result-app
     labels:
      name: result-app-deploy
      app: voting-app
   spec:
     containers:
       - name: voting-app
         image: kodekloud/examplevotingapp_result:v1
         ports:
         - containerPort: 80
         