apiVersion: v1 
kind: Service
metadata:
  name: result-app-service-deploy
  labels:
    name: result-app-service 
    app: voting-app
spec:
  type: NodePort
  selector:
    name: result-app-deploy
    app: voting-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005