apiVersion: v1 
kind: Service
metadata:
  name: voting-app-service-deploy
  labels:
    name: voting-app-service 
    app: voting-app
spec:
  type: NodePort
  selector:
    name: voting-app-deploy
    app: voting-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004